controllers/FieldsController.php
<?php

namespace app\controllers;

use app\models\AllowField;
use app\models\ChannelType;
use app\models\forms\AllowFieldsForm;
use app\models\User;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;

/**
 * Класс для работы с полями
 * Class FieldsController
 * @package app\controllers
 */
class FieldsController extends Controller {
    /**
     * Разрешения
     * @return array
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'delete'],
                        'allow' => true,
                        'roles' => [User::ROLE_ADMIN]
                    ]
                ],
            ]
        ];
    }

    /**
     * Список полей
     * @param $channel
     * @return string
     */
    public function actionIndex($channel) {
        $channelType = ChannelType::findOne(['id' => $channel]);

        $dataProvider = new ActiveDataProvider([
            'query' => AllowField::find()->where(['channel_types_id' => $channel]),
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'channelName' => $channelType->title,
            'channel' => $channel
        ]);
    }

    /**
     * Создание поля
     * @param $channel
     * @return string
     */
    public function actionCreate($channel) {
        $channelType = ChannelType::findOne(['id' => $channel]);
        $model = new AllowFieldsForm();
        $model->channel_types_id = $channel;

        if (\Yii::$app->request->post()) {
            $model->load(\Yii::$app->request->post());

            if ($model->validate()) {
                try {
                    $allowFields = new AllowField();
                    $allowFields->setAttributes($model->getAttributes(), false);
                    $allowFields->save();
                } catch (\Exception $exception) {
                    \Yii::$app->session->setFlash('warning', 'Ошибка при добавлении поля');
                    return $this->redirect(['fields/index', 'channel' => $channel]);
                }

                \Yii::$app->session->setFlash('success', 'Поле успешно добавлено');
                return $this->redirect(['fields/index', 'channel' => $channel]);
            }
        }

        return $this->render('create', [
            'model' => $model,
            'channel' => $channel,
            'channelName' => $channelType->title,
        ]);
    }

    /**
     * Удаление поля
     * @param $channel
     * @param $id
     * @return \yii\web\Response
     */
    public function actionDelete($channel, $id) {
        try {
            AllowField::findOne(['id' => $id])->delete();
        } catch (\Exception $exception) {
            \Yii::$app->session->setFlash('warning', 'Ошибка при удалении поля');
            return $this->redirect(['fields/index', 'channel' => $channel]);
        } catch (\Throwable $e) {
            \Yii::$app->session->setFlash('warning', 'Ошибка при удалении поля');
            return $this->redirect(['fields/index', 'channel' => $channel]);
        }

        \Yii::$app->session->setFlash('success', 'Поле успешно удалено');
        return $this->redirect(['fields/index', 'channel' => $channel]);
    }
}

controllers/TypeController.php
<?php

namespace app\controllers;


use app\models\ChannelType;
use app\models\forms\ChannelTypeForm;
use app\models\User;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\filters\AccessControl;

/**
 * Контроллер для управление типами каналов
 * Class TypeController
 * @package app\controllers
 */
class TypeController extends Controller {
    /**
     * Разрешения
     * @return array
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'delete', 'update'],
                        'allow' => true,
                        'roles' => [User::ROLE_ADMIN]
                    ]
                ],
            ]
        ];
    }

    /**
     * Список типов
     * @return string
     */
    public function actionIndex() {
        $dataProvider = new ActiveDataProvider([
            'query' => ChannelType::find(),
            'pagination' => [
                'pageSize' => 10,
            ],
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Создаеие типа
     * @return string|\yii\web\Response
     */
    public function actionCreate() {
        $model = new ChannelTypeForm();

        if (\Yii::$app->request->post()) {
            $model->load(\Yii::$app->request->post());

            if ($model->validate()) {
                try {
                    $type = new ChannelType();
                    $type->name = $model->name;
                    $type->title = $model->title;
                    $type->save();
                } catch (\Exception $exception) {
                    \Yii::$app->session->setFlash('warning', 'Ошибка при создании типа');
                    return $this->redirect(['type/index']);
                }

                \Yii::$app->session->setFlash('success', 'Тип успешно создан');
                return $this->redirect(['type/index']);
            }
        }

        return $this->render('create', [
            'model' => $model
        ]);
    }

    /**
     * Удаление типа
     * @param $id
     * @return \yii\web\Response
     */
    public function actionDelete($id) {
        try {
            ChannelType::findOne(['id' => $id])->delete();
        } catch (\Exception $exception) {
            \Yii::$app->session->setFlash('warning', 'Ошибка при удалении типа');
            return $this->redirect(['type/index']);
        } catch (\Throwable $e) {
            \Yii::$app->session->setFlash('warning', 'Ошибка при удалении типа');
            return $this->redirect(['type/index']);
        }

        \Yii::$app->session->setFlash('success', 'Тип успешно удален');
        return $this->redirect(['type/index']);
    }

    /**
     * Обновление типа
     * @param $id
     * @return string|\yii\web\Response
     */
    public function actionUpdate($id) {
        $model = ChannelType::findOne(['id' => $id]);
        $form = new ChannelTypeForm();

        $form->setAttributes($model->getAttributes());

        if (\Yii::$app->request->post()) {
            $form->load(\Yii::$app->request->post());

            if ($form->validate()) {
                try {
                    $model->name = $form->name;
                    $model->title = $form->title;
                    $model->save();
                } catch (\Exception $exception) {
                    \Yii::$app->session->setFlash('warning', 'Ошибка при обновлении типа');
                    return $this->redirect(['type/index']);
                }

                \Yii::$app->session->setFlash('success', 'Тип успешно обновлен');
                return $this->redirect(['type/index']);
            }
        }

        return $this->render('update', [
            'model' => $form,
            'id' => $id
        ]);
    }
}

views/fields/create.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

$this->title = 'Новое поле ';
$this->params['breadcrumbs'][] = ['label' => 'Типы каналов', 'url' => Url::to(['type/index'])];
$this->params['breadcrumbs'][] = ['label' => 'Редактирование ' . $channelName, 'url' => Url::to(['type/update', 'id' => $channel])];
$this->params['breadcrumbs'][] = ['label' => 'Список полей ' . $channelName, 'url' => Url::to(['fields/index', 'channel' => $channel])];
$this->params['breadcrumbs'][] = $this->title;

$form = ActiveForm::begin([
    'id' => 'form-create',
    'enableClientValidation' => false,
    'options' => []
]);

?>

<div class="panel panel-default">
    <div class="panel-body">
        <div class="row">
            <div class="col-xs-6">
                <p class="h3">Основная информация</p><br/>
                <?= $form->field($model, 'title') ?>
                <?= $form->field($model, 'name')->input('text') ?>
                <?= $form->field($model,'type')->radioList($model->getTypes()) ?>

                <div class="form-group">
                    <?= Html::submitButton('Создать', ['class' => 'btn btn-primary']) ?>
                </div>
                <?php ActiveForm::end() ?>
            </div>
        </div>
    </div>
</div>

views/fields/index.php
<?php

use yii\grid\GridView;
use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */

$this->title = 'Список полей ' . $channelName;
$this->params['breadcrumbs'][] = ['label' => 'Типы каналов', 'url' => Url::to(['type/index'])];
$this->params['breadcrumbs'][] = ['label' => 'Редактирование ' . $channelName, 'url' => Url::to(['type/update', 'id' => $channel])];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="panel panel-default">
    <div class="panel-heading clearfix">
        <div class="btn-group pull-right">
            <a href="<?= Url::to(['fields/create', 'channel' => $channel]); ?>" type="button" class="btn btn-default">Добавить поле</a>
        </div>
    </div>
    <div class="panel-body">
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'title',
                'name',
                'type',
                [
                    'class' => 'yii\grid\ActionColumn',
                    'header' => 'Действия',
                    'template' => '{delete}',
                    'buttons' => [
                        'delete' => function($url, $model) {
                            return Html::a('<span class="glyphicon glyphicon-trash"></span> Удалить',
                                Url::to(['fields/delete', 'channel' => $model->channel_types_id, 'id' => $model->id]), [
                                'title' => Yii::t('yii', 'Удалить'),
                                'class' => 'btn'
                            ]);
                        }
                    ]
                ]
            ]
        ]) ?>
    </div>
</div>